canonical/raft

configure.ac

Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

build: add common LXC compiler hardening flags

---

src/replication.c

Fix musl compilation

---

Makefile.am
example/server.c
include/raft.h
src/fixture.c
src/log.c
src/raft.c
src/replication.c
src/start.c
src/uv.c
src/uv.h
src/uv_finalize.c
src/uv_list.c
src/uv_metadata.c
src/uv_os.c
src/uv_os.h
src/uv_segment.c
src/uv_snapshot.c
src/uv_truncate.c
test/unit/test_uv.c
test/unit/test_uv_append.c
test/unit/test_uv_list.c
test/unit/test_uv_load.c
test/unit/test_uv_snapshot.c
test/unit/test_uv_truncate.c

Closed segments trail

---

example/cluster.c

Fixes some compiler warnings on buffer sizes

Fix some compiler warnings in the example cluster

---

.travis.yml
configure.ac
src/uv_file.c
src/uv_file.h
test/lib/dir.c
test/lib/dir.h
test/lib/runner.h
test/lib/uv.h
test/unit/test_uv_append.c
test/unit/test_uv_file.c
test/unit/test_uv_finalize.c
test/unit/test_uv_init.c
test/unit/test_uv_os.c
test/unit/test_uv_prepare.c
test/unit/test_uv_truncate.c

Don't require file-system specific test directories

---

include/raft.h
src/raft.c

Add raft_configuration_encode to public API

---

src/replication.c
test/integration/test_demote.c
test/integration/test_transfer.c
test/lib/cluster.h

This allows for graceful leadership transfer.

Prevent leader from stepping down after it has been demoted.

---

src/uv_os.c

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

uv_os: Mark eventfd as CLOEXEC

---

example/server.c

Fix allocation of example server's Fsm

---

src/err.h
src/log.c
src/replication.c
src/uv_segment.c

Fix a few of the warnings reported by Coverity.

Fix some coverity warnings

---

src/uv_os.c

Emulate fallocate() on libc implementations missing a fallback

---

src/recv_request_vote.c

If a removed or spare node still thinks it's a voter it will start an election. This change avoids disrupting the current leader, as discussed in the raft paper.

Don't let voter nodes demoted to spare disrupt the leader

---

src/replication.c

Allocate a separate buffer for each log entry. In this way, large
batches don't stay referenced by a potential small amount of log
entries, that would lead to memory spikes on nodes where IO to
persistent storage is consistently slow.
In 30+ runs of the test script in https://github.com/canonical/dqlite/issues/276, the memory spike has not occurred.
Performance implications are not measurable on my laptop performing 100.000 writes to a single key in a 3-node cluster running with a ramdisk using the adapted dqlite-demo from https://github.com/canonical/dqlite/issues/276.

recv_append_entries: Always free the batch

---

src/uv_snapshot.c

`UvList` calls `UvSnapshotInfoAppendIfMatch` and can run concurrently
on the threadpool with `uvSnapshotPutCb` through a call from `uvSnapshotGetCb`.
This can lead to the `.meta` file being removed for a snapshot that is
not fully created, resulting in an 'orphaned' snapshot file.

uv_snapshot: Don't remove .meta and snapshot files in UvList

---

configure.ac

Release 0.10.1

---

.github/workflows/build-and-test.yml
.github/workflows/cla-check.yml
.github/workflows/coverity.yml
.travis.yml

- Move amd64 builds & tests to github-actions
- Keep non-amd64 builds & tests in Travis

GitHub actions

---

src/compress.c

compress: Fix build for i386

---

src/uv_segment.c

gcc-10 & newer produce the following warning:
‘strncpy’ output may be truncated copying 33 bytes from a string of length 33 [-Werror=stringop-truncation]
95 |   return __builtin___strncpy_chk (__dest, __src, __len,
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
96 |                                   __glibc_objsize (__dest));
|                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
I don't agree with this warning, but fix it anyway, while not resorting back to `strcpy`.
Check return value of `snprintf` and replace `strncpy` by `memset` and `memcpy`.

uv_segment: Replace strncpy

---

.github/workflows/packages.yml

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

github: Tweak git describe call

---

LICENSE

Closes #252
Signed-off-by: Stéphane Graber <stephane.graber@canonical.com>

LICENSE: Add SPDX identifier

---

src/replication.c

Potential fix for https://github.com/canonical/raft/issues/192.
I am not able to reproduce the error from the issue during normal operation, but can reproduce the behavior by calling `UvAppend` with 0 entries, it will lead to closed segments that contain 0 entries in the preamble.
Added a conditional instead of relying solely on the assert.
Will try to reason some more if this situation can actually occur, but for now we should at least protect against it.

replication: Ensure there are entries to append

---

example/server.c
src/uv_segment.c

Fix leak in uvLoadClosedSegment

---

include/raft.h

See https://github.com/canonical/dqlite/issues/220.

raft.h: use enums for #define groups

---

src/uv_tcp_listen.c

uv_tcp_listen: Fix unreachable code path.

---

.github/workflows/build-and-test.yml

github actions: codecov v2 -> v3

---

src/fixture.c
src/replication.c
test/integration/test_replication.c

Closes #320
Closes #314 (confirmed by running Jepsen against this branch)

replication: Give up leadership when a disk write fails

---

src/byte.h
src/configuration.c
src/uv_metadata.c
test/unit/test_byte.c
test/unit/test_configuration.c

byte: Don't bother with aligned byte-access functions

---

.github/workflows/xarch.yml
src/uv_metadata.c

Add a cross-arch CI job

---

amalgamation.json

We should probably automate this.

amalgamation: Add latest source files.

---

src/uv.c

uv: Prevent calling close_cb twice

---

src/uv.c
src/uv_append.c
src/uv_finalize.c
src/uv_snapshot.c
src/uv_truncate.c

WIP -- this causes some tests to fail that I need to look into, but I want to get feedback on this strategy for fixing #324 (and #332?).

uv: Never invoke barrier callback twice

---

.github/workflows/packages.yml

packages: remove bionic, impish; add kinetic

---

include/raft/fixture.h
src/fixture.c
src/recv_request_vote.c
src/replication.c
src/tick.c
test/integration/test_snapshot.c

replication: Fix handling of new term when snapshotting

---

src/replication.c
test/integration/test_replication.c

Another swing at fixing bad accesses to the `current_leader.address` field when a follower updates its term number while entries are being written to disk. This version is significantly simpler than the flawed #351, and I've added a test to cover the new code. Running Jepsen against this branch at https://github.com/canonical/jepsen.dqlite/pull/72 and it looks good so far.
Closes #339 

replication: Don't respond to AppendEntries if term has changed

---

src/lifecycle.c

See https://github.com/canonical/dqlite/pull/457.

lifecycle: Trace request ID if set

---

.github/workflows/build-and-test.yml

github: Remove deprecated Ubuntu Bionic

---

Makefile.am
configure.ac
raft.pc.in

Fixes #375 
Fixes #376
@mdorier, would you mind seeing if this branch fixes the issues you're seeing?

Fix LZ4_CFLAGS and raft.pc

---

CONTRIBUTING

Hopefully this will lead to more people signing the CLA before opening a PR.

Add CONTRIBUTING file.

---

test/integration/test_replication.c

Using functions for assertions has the downside that when a test fails munit will report a line number that points to the assert function, not to the test function, making it more difficult to spot the exact point where the test fails.
When using macros, munit will report the appropriate offending line of the test function (the one where the macro is invoked).

test_replication: turn the assert_config function into a macro

---

test/lib/heap.c

This reverts commit 4c220ec654c325d4f30ee0a938da8facd5d15d83.

Revert "lib/heap: Only count non-NULL allocations."

---

.github/workflows/downstream.yml

Invoke the new downstream checks workflow for PRs

---

.github/workflows/packages.yml

Only publish to the PPA from master

---

README.md
include/raft.h
src/fixture.c
src/tracing.c
src/tracing.h
src/utils.h
test/lib/tracer.c
test/lib/tracer.h

- Removed static qualifier from tracef() to fix potential multithreading bug;
- Added log levels.

Initial log format rework

---

.github/workflows/packages.yml

Depends on the PRs to dqlite-ppa.

github: Update package name
