src/uv_segment.c
This workarounds some upgrade issues from LXD 3.14 to 3.15. Should
be eventually dropped.
=> Ignore errors coming from out-of-range closed segments

src/uv.c, src/uv_segment.c, test/unit/test_uv_load.c
Start cleanly in case an open segment has all entries between the
last closed segment and the last snapshot.
=> Handle open segments with entries up to last snapshot

README.md, configure.ac
Either the stream logger with the standard output, or the ring logger with the buffer size.
=> README: more accurate logger initialization instructions

test/lib/dir.c, test/lib/dir.h, test/unit/test_uv_file.c, test/unit/test_uv_os.c, test/unit/test_uv_prepare.c
=> Attempt to skip tests that rely on the AIO sub-system not being used

configure.ac, src/fixture.c, src/progress.c, src/tick.c, src/uv.c, test/unit/test_uv_writer.c
Somehow fixed the warnings about the possibly uninitialized memory (although Valgrind-memcheck still complains).
But not the warnings about the (set-but-not-)unused variables, because they're actually used in assertions. Don't know why the compiler can't detect that.
Also, the package version shouldn't lag behind, but always point to the coming release.
=> uv: resilience improvements

src/uv_append.c, test/integration/test_uv_append.c
In case there is more than one segment in the pending writes queue, attempt to
schedule the write to the last segment, not the current one, so it gets properly finalize
upon completion.
=> Fix scheduling appends to follow up segments

src/uv.h, src/uv_snapshot.c, test/integration/test_uv_load.c
These snapshots might have failed due to out-of-space errors.
Fixes #126.
=> Ignore empty snapshot data files

.dir-locals.el, .travis.yml, configure.ac, src/syscall.c, src/syscall.h
=> Only include AIO syscall wrappers on Linux

.dir-locals.el, include/raft.h, src/heap.c, src/uv_fs.c, src/uv_segment.c, test/lib/heap.c
This should help ports to other platforms (e.g. Windows, #119) and language bindings (e.g. Rust, #130).
=> Add raft_aligned_free() API for releasing aligned memory

README.md, example/server.c, include/raft.h, src/convert.c, src/election.c, src/election.h, src/raft.c, src/recv.c, src/recv.h, src/recv_request_vote.c, src/recv_request_vote_result.c, src/tick.c, src/uv_encoding.c, test/integration/test_election.c
This prevents partitioned, demoted or removed servers from disrupting the current leader.
Closes #65 .
=> Implement pre-vote extension

src/election.c
When transferring leadership, we should grant our vote to the target leader.
=> Grant out vote to the transferee if we're currently the leader

docs/disk-format.rst, docs/index.rst
This is basically a copy of the docstring in `include/raft/uv.h`.
=> Add documentation about disk format

configure.ac
This makes the unit tests setup the correct expectation about wether direct
I/O is supported or not.
=> Detect the version of the ZFS kernel module instead of the tools

test/lib/fsm.c
This fixes a test regression introduced by #112, where the commands of the test FSM have started to be encoded to little-endian format but not decoded accordingly, making tests fail on s390x.
=> Honor endianness when decoding test FSM commands

src/uv.c
The current logic was buggy as in that case it would have set the start index to
the snapshot index, effectively jumping forward the index.
=> Set start index to 1 when there is a snapshot and only open segments

src/uv_encoding.c, src/uv_encoding.h, src/uv_fs.c, src/uv_fs.h, src/uv_recv.c, src/uv_segment.c, test/integration/test_uv_load.c
Load entries from a segment using a single `read()` call to read the entire segment from disk at once, instead of multiple reads for each batch of entries. Besides being slightly more efficient, this will allow cleaner separation of I/O logic and parsing logic later down the road.
=> Use single read to load a segment from disk

test/lib/dir.h
Fixes building tests with musl libc.
=> test/lib/dir.h: add missing include <sys/types.h>

src/replication.c
=> Fix may be used uninitialized warning

src/recv_append_entries.c
AppendEntries RPC's are ignored during installation of a snapshot.
Free the memory associated to the ignored RPC.
Should help with https://github.com/canonical/dqlite/issues/276
Test script output looks like:
> => Spawning database                                                               
> => Spawning test loops                                                             
> => Monitor the result                                                              
> ==> 20210202-1609: db1=80812 db2=81472 db3=162832 leader=127.0.0.1:9001            
> mykey1|foo=1 loop=1                                                                
> mykey2|foo=1 loop=8074                                                             
> ==> 20210202-1610: db1=100788 db2=94684 db3=121800 leader=127.0.0.1:9001 …
=> recv_append_entries: Fix memory leak

configure.ac
Forgot to bump the library minor version when extending the API.
- Add raft_set_install_snapshot_timeout to API
=> release: 0.10.0

src/uv.c, src/uv_fs.c, src/uv_fs.h, test/unit/test_uv_fs.c
This would resolve https://github.com/canonical/raft/issues/183. A follower can crash if it receives an incomplete snapshot from a leader. The tmp-file approach in this PR tries to ensure only fully written snapshot are ever read and sent to a follower.
=> Dont load partial snapshots

test/lib/munit.c
the `exit` library call is causing a hang, replaced by `_exit` system call which is according to https://stackoverflow.com/questions/5422831/what-is-the-difference-between-using-exit-exit-in-a-conventional-linux-fo the correct way to exit from a child that hasn't `exec`'d (like in our case).
Will open a PR to fix munit.
=> Revive arm64 and ppc64le CI tests

Makefile.am, test/lib/munit.c
`__gcov_flush()` is normally called by the exit handlers that are called in response to `exit`, `exit` however was causing hangs on arm64 and ppc64le, and was replaced with `_exit` in munit. Because `_exit` doesn't call exit handlers, we need to call `__gcov_flush()` ourselves when compiling with code coverage enabled.
~~edit: Will just double-check if ASAN still works as expected with the `exit` --> `_exit` change~~ ASAN still works
=> Fix code coverage

.travis.yml
Coverity issue is interfering with the master build.
see
https://travis-ci.community/t/non-amd64-builds-timing-out-if-script-does-exit-0/10996
=> travis: Run ppc64le arch test on PR instead of master

src/uv.c, src/uv.h, src/uv_fs.c, src/uv_fs.h, src/uv_snapshot.c, test/integration/test_uv_load.c, test/unit/test_uv_fs.c
Fixes https://github.com/canonical/dqlite/issues/289.
Snapshots could be orphaned in certain cases, leading to high disk usage. This is fixed here https://github.com/canonical/raft/pull/193.
This PR will clean up, at init, leftover `snapshot` files that don't have a matching `.meta` file at startup and will also cleanup `.meta` files that don't have a matching `snapshot` file.
=> uv_fs: Remove orphaned snapshot files on init

src/recv_append_entries.c, src/replication.c, src/replication.h, test/integration/test_snapshot.c
Fixes https://github.com/canonical/dqlite/issues/284
=> snapshot: Accept AppendEntries RPCs while taking snapshot

src/uv.c
The PRNG of `rand` was not seeded, causing it to be seeded with 1 every time (see https://linux.die.net/man/3/rand) depending on the implementation of `rand` on the platform, this can result in the same random sequence obtained from `rand` on all nodes,  causing the election timeout to fire at the same moment for all nodes and a cluster that cannot make progress. This would be especially problematic if all nodes start up at the same time.
In a future PR I also want to adapt the election timeout mechanism. At the moment, every tick we check if the random timeout has passed. But the value of the tick is quite large (in case of dqlite 500ms) and there are only so many ticks in an election timeout interval, meaning that the randomness of the election timeout is significantly reduced, …
=> uv: seed the PRNG

.travis.yml, Makefile.am, test/lib/munit.c
While trying to fix the extremely slow CI tests on arm64 and s390x I broke the sanitizer functionality. This PR reverts those changes and fixes the hanging by not enabling sanitizers for arm64 and s390x.
The hanging/slow tests are probably caused by https://github.com/google/sanitizers/issues/1331. Will need to look deeper into this, but for now the sanitizer should at least be functional again.
=> Revert munit changes

src/election.c, src/recv_request_vote.c, test/integration/test_transfer.c, test/lib/cluster.h
Fixes https://github.com/canonical/raft/issues/203.
Skip pre-vote logic when `disrupt_leader` is set. Without this fix a leadership transfer could fail when a `HeartBeat` arrives at a node that has just become `Candidate` as the result of a `raft_transfer`.
=> Raft transfer disrupt

.travis.yml, Makefile.am, configure.ac, include/raft/uv.h, src/compress.c, src/compress.h, src/uv.c, src/uv.h, src/uv_fs.c, src/uv_snapshot.c, test/integration/test_uv_snapshot_put.c, test/unit/test_compress.c
This PR introduces snapshot compression with lz4. Next to compressing the snapshot, there's an additional data integrity check when decompressing the compressed snapshot that in practice should allow help to detect storage corruptions. 
Nodes running compression are compatible with nodes running without compression, data over the wire hasn't changed, this should deal with issues where cluster members are only updated one at a time. The compressed snapshot files are regular `lz4` files (without the .lz4 extension though) that can be decompressed with the `lz4` cli tool.
Fixes https://github.com/canonical/raft/issues/198
@stgraber If this is merged it will probably break some `lxd` builds as there will be a new dependency `liblz4-dev`.
=> Snapshot compress

configure.ac
New release for the snapshot compression changes. Accidentally already made the v0.11.0 tag, so this one becomes v0.11.1.
=> release: v0.11.1

src/uv_segment.c
Fixes https://github.com/canonical/dqlite/issues/301
Path to double-free occurring in LXD CI tests.
https://github.com/canonical/raft/blob/1636e2ec20a8bdf83b50a687ce1b677b2693b5fa/src/uv_segment.c#L523
https://github.com/canonical/raft/blob/1636e2ec20a8bdf83b50a687ce1b677b2693b5fa/src/uv_segment.c#L586
https://github.com/canonical/raft/blob/1636e2ec20a8bdf83b50a687ce1b677b2693b5fa/src/uv_segment.c#L619
The function itself is pretty complex with a lot of `goto`'s , decided not to refactor right now, but could use a refactoring.
=> uv_segment: Fix double-free errors

src/uv_segment.c
Fix coverity issue
*** CID 349299:  Memory - illegal accesses  (UNINIT)
/home/runner/work/raft/raft/src/uv_segment.c: 621 in uvLoadOpenSegment()
615     
616     err_after_batch_load:
617         raft_free(tmp_entries[0].batch);
618         raft_free(tmp_entries);
619     
620     err_after_read:
>>>     CID 349299:  Memory - illegal accesses  (UNINIT)
>>>     Using uninitialized value "buf.base".
621         if (buf.base != NULL) {
622             HeapFree(buf.base);
623         }
624     
625     err:
626         assert(rv != 0);
=> uv_segment: Initialize buf

src/uv.c, test/integration/test_uv_load.c
This issue came up while running the jepsen tests, steps are roughly:
- Node receives snapshot install and deletes all closed segments
preceding the snapshot.
- After installing the snapshot, the node receives AppendEntries and
adds the entries to an open segment.
- Node gets killed.
- Node boots and UvLoad closes the open segment using start_index 1,
ignoring the index of the snapshot that is present in the data dir.
- Node fails to start because the newly closed segment and the snapshot are
inconsistent with a message
`raft_start(): io: last entry on disk has index 383, which is behind
last snapshot's index 3072"`
=> uv: Set start_index correctly when no closed segments present

src/uv_encoding.c
Fixes https://github.com/canonical/raft/issues/219.
In https://github.com/canonical/raft/blob/4c71b9417072b338d885c484a8cfbc9275df21d6/src/uv_encoding.c#L343 `*entries` is allocated but `entries` gets freed instead of `*entries`.
=> uv_encoding: Free correct entries pointer

.github/workflows/build-and-test.yml, .travis.yml, src/progress.c, src/progress.h, src/replication.c, test/integration/test_snapshot.c
There are mentions of high CPU load in some dqlite clusters, one of the causes that has been identified is that a raft leader will try to send a snapshot to an offline node every heartbeat interval. When the snapshot is compressed and rather large, this will lead to constant high CPU load on the raft leader because the leader decompresses the snapshot and then sends it over.
This PR addresses this issue by only sending snapshots to nodes that have replied to AppendEntries RPC's, so that the leader knows they are alive.
I have also snuck in another change that speeds up the CI tests by removing the `-O0` flag.
=> Don't send Snapshots to offline nodes

src/client.c, src/convert.c, src/fixture.c, src/replication.c, test/integration/test_membership.c
Fixes https://github.com/canonical/dqlite/issues/324
A `raft_barrier` came in after the leader with id 1 was removed from the configuration, triggering the assertion that the last log entry of a removed leader's log should be a `RAFT_CHANGE` entry.
```
LIBRAFT src/client.c:337 remove server: id 1
LIBRAFT src/replication.c:98 send 1 entries starting at 31 to server 2 (last index 32)
LIBDQLITE 1633012650556145281 gateway__handle:991 gateway handle
LIBDQLITE 1633012650556164550 handle_query_sql:537 handle query sql
LIBDQLITE 1633012650556353278 leader__barrier:473 leader barrier
LIBRAFT src/client.c:87 barrier starting at 33
LIBRAFT src/replication.c:98 send 1 entries starting at 32 to server 2 (last index 33)
LIBRAFT src/replication.c:472 leader: written 1 entries starting at 32: status 0 …
```
=> Leader removal

src/replication.c, test/integration/test_assign.c, test/integration/test_transfer.c
A leader that is no longer a voter in a newly committed configuration will step down.
closes https://github.com/canonical/raft/issues/234
fixes https://github.com/canonical/dqlite/issues/323
=> replication: Leader step down if non-voter in Cnew

src/convert.c, src/election.c, src/recv_request_vote.c, test/integration/test_election.c
```bash
./test/fuzzy/core liveness/networkDisconnect --seed 0x481a5fb7
```
was a reproducer for the issue described in https://github.com/canonical/raft/issues/196
Also contains another enhancement in https://github.com/canonical/raft/pull/247/commits/ac53ca37ebbe85743424fb8ce91fd97ec57376a7 that cleans up the logic a bit.
=> Pre vote bugfixes

include/raft.h, src/recv_request_vote.c, src/recv_request_vote_result.c, src/uv_encoding.c, test/integration/test_election.c, test/integration/test_uv_recv.c
Fixes the rest of https://github.com/canonical/raft/issues/196, where a Candidate could count the vote in a pre-vote RequestVoteResult RPC as a real vote.
Also included a minor fix where we were accessing a `candidate_state` union after converting to `Follower`, this could lead to weird bugs because we could potentially be overwriting the `candidate_state` members by setting fields in `follower_state`.
=> Include pre_vote field in RequestVoteResponse

src/uv_fs.c, src/uv_writer.c
`UvOsIoGetevents` can return a negative value or another unexpected value that is not handled when asserts are turned off and could lead to erroneous behavior at runtime.
The error paths are untested, currently there's no good way to test these error paths. I could look into a way to mock some of the functions to return errors so that these (and a lot of other) error paths can be tested. The code after the `fail_requests` label should be safe, compiled and ran it with a different version of `uvWriterPollCb` that introduces an error.
=> uv_writer: Handle negative rv of UvOsIoGetevents

test/unit/test_compress.c
This fixes the integer error when running the test suite on the `i386` and `mipsel` 32bit architectures for which Debian and Fedora still build packages. 
Tested by building for i686 (see [build.log](https://kojipkgs.fedoraproject.org//packages/raft/0.11.3/2.fc36/data/logs/i686/build.log))
Fixes #258
=> test/unit/test_compress: Respect 32bit architectures

src/election.c, src/heap.c, src/heap.h, src/raft.c, src/recv.c, src/recv_append_entries.c, src/replication.c, src/uv.c, src/uv_append.c, src/uv_finalize.c, src/uv_fs.c, src/uv_prepare.c, src/uv_recv.c, src/uv_segment.c, src/uv_send.c, src/uv_snapshot.c, src/uv_tcp_connect.c, src/uv_tcp_listen.c, src/uv_truncate.c, src/uv_writer.c
I'd like to make some progress on #119 , and the renaming of the heap functions take up a large part of that PR. Merging it separately is an easy win and makes that work more straightforward and easy to review.
=> Rename Heap*() to RaftHeap*() for Windows compatibility.

test/integration/test_uv_init.c
Should fix https://github.com/canonical/raft/issues/156
=> test/integration/uv: skip init/oom test on tmpfs

src/uv.h, src/uv_append.c, src/uv_snapshot.c, src/uv_truncate.c, test/integration/test_uv_append.c, test/lib/tracer.h
This solves a bug that came up during jepsen tests, it occurs when:
- a server is killed ungracefully (leading to a written open segment in
the directory when the system restarts)
- a snapshot file exists
- no closed segments exist
Because open segments are not closed before writing a snapshot, raft,
when starting up and reading the files in the data directory,
erroneously assumes that all the entries in the open segment are newer
than the entries in the snapshot, while in reality the entries are
already contained in the snapshot, leading to a wrong state.
Closing the current open segments before writing the snapshot ensures
that no old entries can mistakenly be identified as new entries, all
entries in the open segments will be newer than the snapshot.
To close the open segments before …
=> uv: barrier before every snapshot

src/uv_append.c
calling `uvAliveSegmentFinalize(s)` while there are writes against the alive segment in flight could lead to `uvWriterClose` being called twice, leading to a triggered assertion  `src/uv_writer.c:393: UvWriterClose: Assertion '!w->closing' failed.`
This can happen when e.g.:
- write against open segment completes in `uvAliveSegmentWriteCb`
- write triggers a checkpoint 
- checkpoint triggers a raft apply command
- triggers a write against the open segment
- adds write to `poll_queue`
- raft apply command triggers a snapshot
- snapshot triggers finalization of open segment
- causes `uvAliveSegmentFinalize(s)` to be called [here](https://github.com/canonical/raft/blob/ca8b466734e57f3f4e30f2f29da9f5ae02a7efc8/src/uv_append.c#L278)
- leading to the cancellation of requests in the `poll_queue` …
=> uv_append: Don't finalize segment if there are writes in-flight

Makefile.am, src/uv_fs.c, src/uv_os.c, src/uv_os.h, test/unit/test_uv_os.c, test/unit/test_uv_writer.c
Eliminates some Coverity issues.
=> uv_os: Perform a runtime check on file and dir lengths when joining

src/uv_append.c
Fixes an instance of https://github.com/canonical/raft/issues/245.
The callback of the append request being fired by the write completing, could trigger a new append that finalized the segment that was just written to, leading to the assertion being triggered. I was able to reproduce this in a couple of longer running tests, with this fix, the issue disappeared.
=> uv_append: Check if segment wasn't closed in write request cb

Makefile.am, configure.ac, include/raft.h, include/raft/fixture.h, src/fixture.c, src/replication.c, src/uv.c, src/uv.h, src/uv_append.c, src/uv_segment.c, src/uv_snapshot.c, src/uv_work.c, test/integration/test_fixture.c, test/integration/test_snapshot.c, test/integration/test_uv_work.c, test/lib/cluster.h, test/lib/fsm.c, test/lib/fsm.h
This PR introduces:
-  a `raft_io->async_work` method that allows raft to run any workload asynchronously from the main loop.
-  raft_fsm version 2 that introduces the `snapshot_async` and `snapshot_finalize` method. `snapshot_async` is ran through the new `async_work` interface and allows a user of raft to run snapshots out of the main loop.
Updated `version-info` according to https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html
=> Async snapshot

Makefile.am, configure.ac, example/server.c, include/raft.h, src/replication.c, src/uv_append.c, src/uv_segment.c, test/integration/test_fixture.c, test/integration/test_snapshot.c, test/lib/cluster.h, test/lib/fsm.c, test/lib/fsm.h
- Introduce `raft_fsm` version 2 adding `snapshot_finalize`. `snapshot_finalize` allows an implementer to clean up state set by `snapshot`. When `snapshot_finalize` is set, raft assumes no ownership of any of the `raft_buffer`s in the snapshot, the implementer must make sure they are cleaned up. 
In `dqlite` this will be used like this:
`snapshot`: copy WAL, disallow checkpoints from running, copy pointers to database pages to `raft_buffer`s (shallow copy, only pointers are copied, less memory allocation + faster). Not allowing checkpoints allows raft to safely access the database pages without the risk of them being changed. `dqlite` writers can still append to the WAL, as we have made a copy.
`snapshot_finalize`: allow checkpoints to run again, free allocated buffers.
- Bumped version …
=> Snapshot finalize

src/compress.c, test/unit/test_byte.c, test/unit/test_compress.c
`dqlite` snapshots will start to present buffers to raft that can have 0 length and contain a base pointer that is NULL because the WAL will be contained in a separate buffer during a snapshot and the WAL can have 0 size, so ensure these cases are tested.
An added constraint in this PR is that the total size of buffers that will be compressed must be larger than 0, this is a workaround for a bug in `liblz4` on bionic.
=> test_compress: Mix in 0 length buffers in tests

include/raft/uv.h, src/uv_tcp.c, src/uv_tcp.h, src/uv_tcp_listen.c, test/integration/test_uv_tcp_listen.c
This allows an application to choose which network interface the
listening socket will bind to.
Closes #273.
Signed-off-by: Roger A. Light <roger@atchoo.org>
=> Add raft_uv_tcp_set_bind_address().

src/uv_fs.c, test/integration/test_uv_init.c, test/unit/test_uv_fs.c
Closes https://github.com/canonical/go-dqlite/issues/183
=> uv_fs: More clear errmsg when UvFsProbeCapabilities fails

include/raft/uv.h, src/uv.c, src/uv.h, src/uv_fs.c, src/uv_fs.h, src/uv_segment.c, test/integration/test_uv_load.c, test/unit/test_uv_fs.c
This PR attempts to move corrupt segment files out of the way at startup. Once moved out of the way, the next startup can complete successfully requiring no manual intervention. The renamed files are named "corrupt-{timestamp}-{filename}" and are kept around in case they would contain useful data.
The logic is as follows:
- open segments: Are basically only renamed in case of an invalid format header, the other cases are already covered. If an open segment is corrupt, the other open segments are renamed too. In case they contained valid data, raft wouldn't attempt to load the data, because loading it could lead to missing transactions that were part of the corrupt segment leading to an inconsistent state of the log.
- closed segments: Are renamed when they are corrupt and if they are the …
=> Startup recovery

include/raft.h, include/raft/fixture.h, src/fixture.c, test/integration/test_fixture.c, test/lib/cluster.h
Accessing the client-supplied `struct raft_fsm` array can cause memory
errors when the client was compiled against a raft version with an
older, smaller `struct raft_fsm` version when using `raft_fixture_init`.
This happens because the new raft library will stride through the array with the new size,
while the binary, compiled against an older version, will only allocate space
for the old size, this results in corruptions.
=> Deprecate raft_fixture_init

Makefile.am, include/raft.h, include/raft/fixture.h, src/fixture.c, src/raft.c, src/replication.c, src/uv.c, src/uv.h, src/uv_snapshot.c, src/uv_work.c, test/integration/test_init.c, test/integration/test_snapshot.c, test/integration/test_uv_work.c, test/lib/cluster.h, test/lib/fsm.c, test/lib/fsm.h
Same functionality as in (reverted) https://github.com/canonical/raft/pull/268 , but decided to open a new PR for clarity.
As discussed, this is needed for dqlite's disk-mode, copying a multi GB database in the main loop would be disastrous.
I will not be porting dqlite's regular memory operation mode to async snapshots as it's not needed imo and limits some risks.
=> Async snapshots

test/integration/test_uv_tcp_connect.c
Closes https://github.com/canonical/raft/issues/292
A change introduced in `libuv 1.44.2` causes the write of the handshake data to complete after a single loop iteration, not allowing us a chance to close between the invocation of `uv_write` and the invocation of the `uv_write_cb`. Decided to disable the test for uv versions 1.44.2 and higher.
=> test_uv_tcp_connect: Disable test for certain uv versions

src/uv_ip.c, src/uv_ip.h, src/uv_tcp_connect.c, test/integration/test_uv_tcp_connect.c
As first step to allow usage of hostnames instead of static IPs I added the required additional async getaddrinfo step to the outgoing tcp connection to the other cluster members.
Unfortunately the libuv async getaddrinfo is not connected to the TCP handle. As a consequence abort the connect got a little bit more complicated as the getaddrinfo may be in progress and cannot be stopped. In this case the data structures need to be valid until the getaddrinfo callback is finished.
In the current first implementation the getaddrinfo is restricted to IPv4 addresses in a string representation as before. This way it should behave excactly as before.
=> Add additional async getaddrinfo step to outgoing tcp connections

src/uv.h, src/uv_append.c, src/uv_segment.c, test/integration/append_helpers.h, test/integration/test_uv_append.c
Should prevent issues like: https://github.com/canonical/raft/issues/304
=> Uvappend 8-byte alignment

test/integration/append_helpers.h
#305 introduced a test with unaligned log entries, but the ENTRIES macro in test/integration/append_helpers.h can generate an unaligned access in this situation.
Should fix the latest Launchpad build failures.
=> test/integration/append_helpers: Fix unaligned access

include/raft.h, src/heap.c
As part of working on https://github.com/canonical/dqlite/pull/395, I'm trying to add some tests that inject failures of raft_malloc and co., similar to what's already set up for the sqlite3 allocator [here](https://github.com/canonical/dqlite/blob/master/test/lib/heap.c). To implement that, we need (read-only) access to the *current* raft_heap, so that our fault-injecting raft_heap can defer to the original allocator as needed (and so that it's possible to restore the original allocator).
To that end, add a new function `struct raft_heap *raft_heap_get(void)` to raft.h, implemented by simply returning `currentHeap`. We explicitly disallow using the returned pointer to mutate the default allocator.
=> heap: Add raft_heap_get

Makefile.am, src/uv_ip.c, src/uv_ip.h, src/uv_tcp.c, src/uv_tcp.h, src/uv_tcp_connect.c, src/uv_tcp_listen.c, test/integration/test_uv_tcp_connect.c, test/integration/test_uv_tcp_listen.c, test/lib/addrinfo.c, test/lib/addrinfo.h, test/lib/tcp.c, test/lib/tcp.h
This is the second PR to finalize hostname support for the raft library. This will close https://github.com/canonical/raft/issues/298
=> Feature hostnames

.github/workflows/build-and-test.yml, .github/workflows/coverity.yml
- Update checkout action to v3. Fixes a Github warning for using Node 12.
- Add ubuntu 22.04 to test matrix. Github is phasing out support for ubuntu 18.04 in april 2023 https://github.com/actions/runner-images/issues/6002 Tests on 18.04 will fail during the "brown-out" periods until then. Add ubuntu 22.04 to test suite to prep for removal of 18.04.
=> update github actions

Makefile.am, configure.ac, src/assert.h
More than once while looking at an assertion failure in Jepsen logs I've wished that it came with a backtrace -- this PR implements that.
Specifically, if RAFT_ASSERT_WITH_BACKTRACE is defined during compilation, we call into [libbacktrace](https://github.com/ianlancetaylor/libbacktrace) to print a symbolic backtrace before aborting. I still need to add the build system stuff to enable/disable this feature, find libbacktrace, and pass the appropriate flags during compilation.
=> Support printing backtrace when an assertion fails

src/replication.c
=> replication: Initialize version for AppendEntriesResult

src/replication.c
Should already fix https://github.com/canonical/raft/issues/339
Follow up in https://github.com/canonical/raft/issues/343
=> replication: Only send AppendEntriesResult when FOLLOWER

src/uv.c
This reverts commit c042b4ebb8f04c642357a2a94570ca11f011c367.
dqlite tests are not very happy with the change:
```
LIBDQLITE 1671181712620064690 maybeCheckpoint:130 wal size (2) < threshold (1000)
LIBDQLITE 1671181712620151091 leaderApplyFramesCb:236 apply frames cb
LIBDQLITE 1671181712620161391 leaderMaybeCheckpointLegacy:182 leader maybe checkpoint legacy
LIBDQLITE 1671181712620209491 clientRecvResult:219 client recv result fd 15 last_insert_id 0 rows_affected 0
LIBDQLITE 1671181712620222891 clientClose:42 client close fd 15
LIBDQLITE 1671181712620241991 dqlite_node_stop:753 dqlite node stop
LIBDQLITE 1671181712620267292 conn__stop:330 conn stop
LIBDQLITE 1671181712620282892 gateway__close:80 gateway close
LIBDQLITE 1671181712620295592 leader__close:143 leader close
LIBDQLITE …
```
=> Revert "uv: Prevent calling close_cb twice"

src/uv.c
This is related to #341 -- just trying to catch a bit earlier the situation where uvMaybeFireCloseCb somehow runs to completion more than once. 
=> uv: Clear io->impl when it's freed

src/replication.c
Closes #338. After thinking about it for a while, I've convinced myself that appendLeaderCb can just skip truncating the log if the appended entries (for which the disk write was cancelled) are not present, because this can occur in a totally benign way. For example, we could start an append request for an entry at index 16 and then start another for index 17 before the first request is finished. Then we could cancel those two requests in the same order they were submitted, and the appendLeaderCb for the second request won't see any entry at index 17 to be truncated. And in fact this seems to be just what happened to cause that Jepsen failure.
(It would be elegant to cancel queued requests in LIFO order, so that each callback sees the log in the same state it was just after it appended …
=> replication: Tweak applyLeaderCb cleanup

src/replication.c, src/tick.c, test/integration/test_snapshot.c
Closes #343. @MathieuBordere, let me know if this wasn't what you had in mind, I'm sure there are other possible approaches. 
=> tick: Don't convert to candidate while a snapshot is installing

src/replication.c
This should avoid some potential problems when r->follower_state.current_leader changes between receiving a request and calling sendAppendEntriesResult (e.g. the latest manifestation of #339).
=> replication: Drop append entries result if a state transition has occurred

src/byte.c
silences a warning when `byteSha1Update` is called with a 1 byte buffer. The line with the silenced warning will never be called because to enter the for loop `i + 63` has to be smaller than `len`, but `len` is `1` and `i` is unsigned, `i + 63` will never be smaller than `1`, so the code is unreachable in that case.
Fixes kinetic builds for raft on ppc64el.
Full diagnostic:
```
In function ‘byteSha1Update’,
inlined from ‘byteSha1Digest’ at src/byte.c:358:5:
src/byte.c:318:13: error: ‘byteSha1Transform’ reading 64 bytes from a region of size 0 [-Werror=stringop-overread]
318 |             byteSha1Transform(s->state, &data[i]);
|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/byte.c:318:13: note: referencing argument 2 of type ‘const uint8_t[64]’
src/byte.c: In function …
```
=> byte: Ignore false positive stringop-overread warning

include/raft.h, src/configuration.c, src/configuration.h, src/membership.c, src/raft.c, src/replication.c, src/snapshot.c, src/start.c, test/integration/test_replication.c
This PR introduces the following changes:
* Set `configuration_uncommitted_index` upon startup as we can't know if the configuration is committed or not.
* Backup the configuration in case the configuration entry is no longer present in the log.
1. After taking a snapshot and before purging entries from the log.
2. After installing a snapshot in case the next config needs to be rolled back.
* Only store committed configurations in a snapshot and not the latest available configuration.
Fixes https://github.com/canonical/raft/issues/250
=> Config rollback

src/byte.c
Inlining seems to cause a false-positive stringop-overread warning on ppc64le, as this is not performance sensitive code in real-world systems, it's okay to not inline this function.
=> byte: Don't inline byteSha1Update

raft.pc.in
This partially reverts #377 and #378 -- the Requires.private line is causing builds to fail on Launchpad.
=> Revert addition of Requires.private to raft.pc

include/raft.h, src/state.c
I found myself needing this during my work on server-side role management for dqlite -- when a node is shutting down, it's expected to check whether it's a voter, and if so to promote another node into that role before going offline.
=> Expose an accessor for the current Raft role

include/raft.h
This branch adjusts a few comments and docstrings in `raft.h` to fit the 80 characters line limit, and runs `clang-format` against the whole file.
We have `.clang-format` file in the top-level directory of the source tree. It's basically the equivalent of `gofmt` in Golang, and helps keep the code layout consistent. We might tweak the configuration options in `.clang-format` if there are styles we want to change.
We might also consider adding a Github workflow lint action like https://github.com/marketplace/actions/clang-format-lint, or something along those lines.
=> clang-format of raft.h

include/raft.h, src/membership.c, src/membership.h, src/raft.c, src/replication.c, src/snapshot.c, src/start.c, test/integration/test_assign.c, test/integration/test_membership.c
This should make it more clear that the index refers to the last committed configuration, as opposed to any pending uncommitted configuration, which is tracked by `configuration_uncommitted_index`.
See also this comment https://github.com/canonical/raft/pull/409#issuecomment-1516644987.
=> Rename configuration_index to configuration_uncommitted_index

include/raft.h
See also libuv:
https://github.com/libuv/libuv/blob/3f331e97da5b1cc2e24765dcb6d26c9dd313418f/include/uv.h#L34
=> raft.h: Allow overriding RAFT_API

src/configuration.c, src/configuration.h, test/unit/test_configuration.c
This improves documentation of `configurationCopy` and `configurationAdd` and also fixes a couple of memory leaks that could happen in case of errors.
See the individual commit messages for more details.
=> Cleanup failure modes of configurationCopy and configurationAdd

src/configuration.c, src/configuration.h, src/membership.c, src/start.c, src/uv_encoding.c, src/uv_snapshot.c, test/unit/test_configuration.c
This branch sports a few cleanups of the various functions in `src/configuration.{c,h}`. It's mainly about error reporting/propagation and memory leaks. Please review the individual commit messages and diffs for details.
=> Clean-up configuration.h functions

src/replication.c, test/integration/test_replication.c
This fixes #355, see the reproducing test and commit messages for details.
=> Fix last_applied failing assertion

test/integration/test_uv_load.c, test/unit/test_uv_fs.c
The load/openSegmentWithNoAccessPermission and UvFsProbeCapabilitie/noAccess tests would fail when running as root, since EACCES wouldn't be returned.
=> test: Skip permission-related tests when running as root

.github/workflows/build-and-test.yml, .github/workflows/configure.yml
This set of commits adds a new `configure.yml` GitHub actions workflow which is meant to exercise the `./configure` script with various flags under various scenarios.
It's basically intended to become a more comprehensive version of the former `build-nolz4-fail` job in the `build-and-test.yml` workflow.
There are already a few new scenarios that are being tested that were not covered before, and if this gets merged I'd like to add more checks.
Having a separate workflow makes it a bit easier to spot the failure when something goes wrong.
This workflow runs on ubuntu 22.04, instead of 20.04 as the former `build-nolz4-fail` job.
Please see individual commits for more details.
=> Add new configure.yml workflow

configure.ac
The lz4 upstream project has had pkg-config support since about 9 years:
https://github.com/lz4/lz4/commit/dc107107f73942574a0b2d1d9c1edd05b0ff1796
which is included in the r120 release from July 2014.
(the first lz4 release which isn't labeled with the rNNN pattern is v1.7.3 from November 2016, see https://github.com/lz4/lz4/tags?after=v1.8.0).
The oldest lz4 release still in the Ubuntu archive is r131, from 2015, see:
http://archive.ubuntu.com/ubuntu/pool/main/l/lz4/?C=M;O=A
which was included in Ubuntu 16.04 and sports pkg-config support.
It's safe to assume than any real-world consumer will have an lz4 version with pkg-config support.
=> configure: Use only pkg-config to detect lz4

.github/workflows/configure.yml, configure.ac
This change improves `./configure` in a few ways:
- lz4 detection via pkg-config is performed only when it makes sense (i.e. when libuv is available and --without-lz4 is not passed)
- the documentation and checks for --enable-uv / --disable-uv are now more clear about the fact that these flags are about enabling or disabling compression by default, not about enabling or disabling compression support altogether (which is controlled by --with-lz4 / --without-lz4)
- several tests have been put in place to ensure that ./configure succeeds or fails as expected in a number of scenarios
The changes of individual commits should be a bit easier to parse than the full change set.
With these improvements combined, this fixes #441.
=> Skip lz4 check when unnecessary

Makefile.am, src/uv.h, src/uv_append.c, src/uv_finalize.c, src/uv_snapshot.c, src/uv_truncate.c, test/integration/test_uv_append.c, test/integration/test_uv_truncate_snapshot.c
Related to https://github.com/canonical/raft/issues/372 and possibly https://github.com/canonical/raft/issues/431
The test in this PR fails because when all active open segments are already involved in a barrier, the next barrier will fail to be attached to an open segment and the barrier callback will never fire. My first - hacky - idea, would be to push a new open segment and attach the barrier to that one. Any other inspiration?
=> Fix callback for second barrier not being attached

src/uv_append.c
should help debug #450 
rolling back uv->append_next_index after a segment prepare failure seems to be incorrect in some cases.
=> uv_append: trace failed segment prepare.

include/raft/fixture.h, src/fixture.c, src/replication.c, test/integration/test_replication.c, test/lib/cluster.h
=> replication: Cancel correct request type when append fails.

src/uv_append.c
Fixes #461.
`barrier->blocking` was not initialized, resulting in `barrier->blocking` being `true` in most of the cases, causing the effect seen in the issue.
The tests didn't catch the bug as the barriers are properly initialized in the tests.
edit: not going to spend time on test for now.
~~Will still add a test that uses a slow `UvSnapshot` call and ensures append requests get through.~~
=> uv_append: Initialize barrier upon creation.

include/raft.h, src/convert.c, src/recv_timeout_now.c, src/replication.c, src/tick.c, test/integration/test_election.c
Fixes #386, reviving the approach from #464 as the first part of the approach worked out in the discussion of #465.
I'm not entirely happy about adding the append_in_flight_count field to `struct raft` -- it would be more principled to query our raft_io for this information. On the other hand, adding a method for that is a more invasive change that breaks compatibility with older raft_io implementations. So I'm undecided on the best design here.
=> Don't convert to candidate while entries are being persisted, take 2

src/replication.c, src/uv_append.c, src/uv_finalize.c, test/integration/append_helpers.h, test/integration/test_replication.c, test/integration/test_uv_append.c
- Truncate follower log when append entries fail to persist.
- When the segment write fails:
- ~~Reset open segment so it's ready for new writes.~~ Mark the segment for finalizing.
- Cancel queued append requests because raft assumes all writes are in order and succeed, otherwise the log index accounting will be off and append entries will be missing on disk, leaving a 'hole' and inconsistent  data.
fixes #450 (It hasn't occurred in 20ish Jepsen runs of 78 tests)
Will still try to exactly replicate the error in the tests.
=> Handle segment write failures

src/uv.c, src/uv.h, src/uv_fs.c, src/uv_fs.h, src/uv_os.c, src/uv_os.h, src/uv_prepare.c, test/unit/test_uv_fs.c, test/unit/test_uv_writer.c
With the default segment size, and a blocksize of 4KB, the fallocate emulation code could perform 2048 synced writes leading to a lot of latency. Instead, sync the file once after writing without O_DSYNC. and reopen the file with O_DSYNC before giving the fd back to raft. Detect fallocate capabilities at startup.
=> uv_fs: Don't do synced writes when emulating fallocate

src/client.c, src/progress.c, src/progress.h, src/replication.c
Receivers of the "timeout now" message ignore the message if their in-memory logs are not up-to-date or if they are persisting log entries. When the message is ignored, the sender will not retry it which can lead to failed leadership transfers that could have been avoided. Instead, let the leader only send the message when it knows the follower has persisted all log entries, based on the follower's match_index.
Fixes https://github.com/canonical/go-dqlite/issues/271. I can no longer reproduce that bug while it was easy to reproduce without the fix.
=> client: Only send timeout now message if persisted state is up-to-date.

src/uv_fs.c, test/unit/test_uv_writer.c
=> uv_fs: EAGAIN is no hard error when probing Async IO.

include/raft/fixture.h, src/fixture.c, src/log.c, src/log.h, src/replication.c, test/integration/test_election.c, test/integration/test_replication.c, test/lib/cluster.h
=> replication: Try to reinstate entries that have been truncated away

src/tracing.c
results in aligning dqlite's and raft's logs like:
```
LIBRAFT  [3871330] 2023-12-14T09:13:36.850973847 3871336 DEBUG   uvBarrierClose       src/uv_append.c:946 uv barrier close
LIBDQLITE[3871330] 2023-12-14T09:13:36.850977103 3871336 DEBUG   impl_close           src/transport.c:208 impl close
LIBRAFT  [3871330] 2023-12-14T09:13:36.850979067 3871336 DEBUG   uvMaybeFireCloseCb   src/uv.c:160 uv maybe fire close cb
LIBRAFT  [3871330] 2023-12-14T09:13:36.850982754 3871336 DEBUG   uvMaybeFireCloseCb   src/uv.c:160 uv maybe fire close cb
LIBRAFT  [3871330] 2023-12-14T09:13:36.850984787 3871336 DEBUG   uvMaybeFireCloseCb   src/uv.c:160 uv maybe fire close cb
LIBRAFT  [3871330] 2023-12-14T09:13:36.850987242 3871336 DEBUG   ioCloseCb            src/raft.c:121 io close cb
LIBDQLITE[3871330] …
```
=> tracing: Align raft log message with dqlite log message.

Makefile.am, include/raft.h, src/convert.c, src/raft.c, src/tick.c, test/integration/test_voter_contacts.c
This returns the number of voting nodes that are recently in contact with the leader, to allow determining if the cluster is currently in a degraded / at risk state.
I'd be interested on your thoughts on this. At the moment it feels like not being able to find out this information is an omission.
=> Add raft_voter_contact()
